src/style.scss, src/ui/control-panel.ts
Fixes: #9 
This PR adds the following keyboard shortcuts:
- I - invert selection
- Space - toggle splat debug rendering
- Backspace - delete selected splats
Also show application version in title screen and link to github repo on click.
=> UI additions

package-lock.json, package.json, src/asset-loader.ts, src/editor-ops.ts, src/style.scss, src/ui/control-panel.ts
This PR adds an import option to enable loading and saving the scene spherical harmonic coefficients as follows:
NOTE: the spherical harmonic data is currently just _blind data_ - the lighting won't be rotated along with the rest of the scene. This support will come in a followup PR.
=> Optionally load and save sh coefficients

src/asset-loader.ts, src/editor-ops.ts, src/ui/control-panel.ts
We can choose to load only the used subset of data from PLY files, thereby saving large amounts of browser memory.
This PR sets the default to load all data.
=> Load all ply data by default

src/editor-ops.ts, src/main.ts, src/ui/control-panel.ts, src/ui/editor.ts
This PR:
- Display a message when navigating away from page with unsaved changes
- Handle meta/ctrl keys correctly
- Add the option of specifying a remote-storage destination by URL param
When remote storage details are specified these are used during export.
In addition, the export buttons indicate cloud upload:
=> SuperSplat updates

package.json, src/main.ts, src/manifest.json, src/ui/control-panel.ts
Now, when you install the SuperSplat PWA, PLY files will be associated with the app. Here is what that looks like on Windows:
In the video about, I already have Paint3D associated with .PLY, so I use 'Open With' instead. I _could_ switch the SuperSplat PWA to always open .PLY instead, of course.
Fixes #91
=> Associate PLY file with the SuperSplat PWA

package-lock.json, package.json, src/camera.ts, src/controllers.ts, src/custom-shadow.ts, src/edit-ops.ts, src/editor.ts, src/element.ts, src/events.ts, src/file-handler.ts, src/main.ts, src/model.ts, src/scene.ts, src/selection.ts, src/shortcuts.ts, src/splat-convert.ts, src/splat-debug.ts, src/splat.ts, src/style.scss, src/tools/transform-tool.ts, src/ui/control-panel.ts, src/ui/editor.ts, src/ui/popup.ts, src/ui/shortcuts-popup.ts, src/ui/toolbar.ts, tsconfig.json
This PR:
* adds initial support for loading and editing multiple splats
* place file handling under file menu popup (see screenshot below)
* use File System Api for loading and saving files when available 
* grandad Safari still uses the old file download path
* update to playcanvas [engine v1.71.5](https://github.com/playcanvas/engine/releases/tag/v1.71.5)
* bump package minor version
=> Support loading multiple splats and use File System Api

package-lock.json, package.json, src/camera.ts, src/drop-handler.ts, src/file-handler.ts, src/main.ts, src/style.scss, src/tools/transform-tool.ts, src/ui/editor.ts
This PR:
* sizes the transform gizmos to be consistent in screen space
* adds an invisible dom element over the canvas which listens for pointer down and sets the focus to the body (this is to solve the issue where interacting with radio buttons etc results in lost keyboard focus)
* make the entire body drop target instead of only canvas area
=> Make gizmo consistent size, update key focus

package-lock.json, package.json, src/camera.ts, src/controllers.ts, src/file-handler.ts, src/infinite-grid.ts, src/main.ts, src/scene.ts, src/splat.ts, src/style.scss, src/tools/brush-selection.ts, src/tools/picker-selection.ts, src/tools/rect-selection.ts, src/ui/data-panel.ts, src/ui/editor.ts, src/ui/histogram.ts, src/ui/popup.ts
This PR:
* adds a bounding box indicator to the currently selected splat
* replaces the existing grid with an infinity-style version
* updates to the latest [engine v1.73](https://github.com/playcanvas/engine/releases/tag/v1.73.0)
* improves editor performance on large scenes when many splats have been deleted by removing the deleted splats from sorting and rendering
* finally addresses the issue where keyboard shortcuts sometimes don't work correctly
* bump package version
=> New grid, bounding boxes, perf improvements and more

package-lock.json, package.json, src/editor.ts, src/scene-config.ts, src/scene.ts, src/style.scss, src/tools/transform-tool.ts, src/ui/editor.ts, src/ui/view-cube.ts
This PR:
* adds a new "View Cube" widget for fast snapping of the camera to world axes
* bumps package version
=> Add view cube

package-lock.json, package.json
This PR:
* update to latest engine [v1.73.1](https://github.com/playcanvas/engine/releases/tag/v1.73.1), which includes a bugfix for splats going missing after delete
* bump package version
=> Latest engine

package-lock.json, package.json, src/camera.ts, src/editor.ts, src/splat.ts, src/ui/view-panel.ts
Fixes: #164
This PR:
* adds the option to hide splat bound.
* fixes a bug where selection in rings mode was wrong with debug rendering disabled.
* bump package version.
=> Add option to show splat bounding box

package-lock.json, package.json, src/camera.ts, src/editor.ts, src/sh-utils.ts, src/splat-convert.ts, src/splat.ts, src/ui/view-panel.ts
Fixes: #159
This PR:
* adds option to render with spherical harmonics
* available under view panel
* rotates spherical harmonics correctly on export
* bump package to version v1.2.0
Without spherical harmonics:
With spherical harmonics:
=> Support spherical harmonics

package-lock.json, package.json, rollup.config.mjs, src/index.html, src/sw.ts
Fixes: #166
Scss plugin struggles (bugs) when scss imports are encountered on windows.
This PR updates rollup build to output a css file instead and include it in html which happens to also work on windows.
=> Update css build

src/camera.ts, src/controllers.ts, src/editor.ts, src/scene-config.ts, src/scene.ts, src/splat.ts
This PR updates the camera implementation in preparation for #176 
The following changes are made:
- remove legacy config and camera implementation for options we no longer need or use (enable flags/auto rotate)
- handle camera correctly under varying fov (i.e. maintain correct zoom min, max, distance)
- small shader speedup
=> Camera cleanup

package-lock.json, package.json, src/camera.ts, src/editor.ts, src/main.ts, src/scene-config.ts, src/ui/style.scss
This PR:
- updates the handling of URL param config overrides to correctly handle vec3 and color types
- applies the background color config value correctly
- adds new config options to control grid and bound visibility and number of sh bands
- bumps package to v1.2.3
For example, with the following URL, grid and bound is initially hidden with a reddish background:
``` url
https://playcanvas.com/supersplat/editor?show.grid=false&show.bound=false&bgClr=0.5,0.2,0.2
```
=> Expose bg color, grid, bound URL params

src/camera.ts, src/edit-history.ts, src/edit-ops.ts, src/editor.ts, src/main.ts, src/scene.ts, src/selection.ts, src/splat-convert.ts, src/splat-debug.ts, src/splat-state.ts, src/splat.ts, src/tools/move-tool.ts, src/tools/rotate-tool.ts, src/tools/scale-tool.ts, src/tools/transform-tool.ts, src/ui/data-panel.ts, src/ui/splat-list.ts, src/ui/transform.ts
This PR:
* places selection edits in the undo history
* pivot placement is also added
* render debug overlay from splat data directly (instead of building and updating separate copy of data)
=> Add selection updates to undo history

src/shaders/splat-shader.ts
For extremely large scenes (like those generated by MCMC) quite often splats land inside the camera clipping planes and so the scene does not render.
This PR changes the shader clamp the splats to the front and back clipping planes so the splats are always rendered.
=> Ensure splats on front and back clipping planes are not clipped

src/editor.ts, src/main.ts, src/ui/localization.ts, src/ui/view-panel.scss, src/ui/view-panel.ts
Fixes: #215
This PR:
- adds a color selector for the background to the VIEW OPTIONS panel
Notes:
- the selected background color isn't currently saved. this should be done along with all the other settings
- the background color is used when taking screenshots
- the pcui color picker box is placed awkwardly and only hides itself when clicking on the parent panel
=> Add background color picker

src/splat.ts
This PR fixes SH material not being correctly configured.
This was broken recently with the move to PlayCanvas engine v2.
=> SH rendering fix

src/templates/viewer-html-template.ts
This PR:
- adds control helper text popup to the bottom right of the viewer window
- updates the camera frame to work correctly
=> Viewer export updates

src/main.ts, src/tools/brush-selection.ts, src/tools/polygon-selection.ts, src/ui/localization.ts, src/ui/scss/style.scss
Followup PR to #261:
- brush and polygon tool use same html canvas for generating mask
- use 'p' for polygon tool keyboard shortcut ('r' used for picker/rect tool)
- small tweaks on polygon tool:
- use 8px distance to close polygon
- small double click change
- added localisation for remaining languages
=> Polygon tool tweaks

src/main.ts, src/tools/lasso-selection.ts, src/ui/bottom-toolbar.ts
This is the lasso-selection without reorganizing the code of the selection-tools
https://github.com/user-attachments/assets/e0829bad-6ac6-4fbe-834f-445d2b7452b3
=> Simple Lasso-Selection

src/controllers.ts, src/drop-handler.ts, src/file-handler.ts, src/index.html, src/tools/brush-selection.ts, src/ui/editor.ts, src/ui/localization.ts, src/ui/scss/style.scss
This PR updates the trackpad camera controls to finally be usable:
- two finger swipe to orbit
- shift to pan
- ctrl to zoom
Also fix various little issues:
- handle the case when user drops not-files into the application
- test for presence of serviceWorker before attempting to use it
- use alt and cmd key for brush resize to keep consistent camera controls (cc @simonbethke)
Notes:
- unfortunately windows trackpad often limits swipes to one of the two axes, making it less useful than mac for camera control. this can't be fixed according to https://issues.chromium.org/issues/41468861
- tested on:
- macos: chrome, safari, firefox
- windows: chrome, firefox
- firefox wheel mouse detection doesn't work properly. use middle mouse click to zoom instead.
=> Fix touchpad camera controls

src/camera.ts
Fixes: #286 
Clipping near and far were being incorrectly calculated when the scene is behind the camera.
=> Fix for inverted camera

src/templates/viewer-html-template.ts
The gsplat shader has a bug where negative colors are tonemapping incorrectly.
This PR switches to NEUTRAL tonemapping in the viewer to overcome that issue until the fix is available.
=> Workaround tonemapping bug in viewer html

src/splat.ts
This PR:
* updates the sort order of splats to based on their furtherst bounding box extent, instead of the bounding box center
* this results in much better render order for large and overlapping splats
Before:
After:
=> Update splat sorting

src/ui/data-panel.ts, src/ui/histogram.ts
This PR:
- updates the SPLAT DATA panel to make available all the data loaded from the PLY
- though the 45 spherical harmonic coefficients since leaving them in would clutter the dropdown for little benefit
- small fix for NaN bucket calc
=> Histogram panel update

src/splat-serialize.ts
Fixes: #338
2dgs scenes can have `-Infinity` scales which weren't being correctly clamped during export.
=> Fix for compressed.ply export

src/outline.ts, src/selection.ts, src/splat.ts
This PR:
- changes the display to show selected gaussians on the active splat only (instead of rendering yellow/outline on all splats)
- slight cleanup of selection logic
=> Show selection on the active splat only

src/main.ts, src/ui/menu.ts, src/ui/shortcuts-popup.ts
Revert back to `shift + a` for select none since `shift + ctrl + a` clashes with browser shortcut on Windows.
=> Shortcut update for select none

src/camera.ts, src/editor.ts, src/shaders/splat-shader.ts
When picking gaussians in rings mode, only the top layer of gaussians were ever considered for adding/removing/setting the selection.
This has meant it is not possible to select anything other than the top layer of gaussians. Also, it has not been possible to deselect gaussians that are embedded within the scene, since the top layer of gaussians block picking.
This PR updates the picking logic to be much more useful and behave more consistently:
- when adding to the selection (shift), only consider unselected gaussians
- this means it's now possible to add gaussians to the current selection layer at a time
- when removing from the current selection (ctrl), only consider the currently selected gaussians
- so unselecting "blocked" gaussians is now possible
- when setting the selection, do …
=> Rings mode picker update

src/splat-serialize.ts
This PR fixes an issue duplicating/separating splats when part of the model is frozen.
See https://discord.com/channels/408617316415307776/1275850227663769686/1318674627496775700 for more.
=> Duplicate fix

src/outline.ts, src/shaders/outline-shader.ts, src/shaders/splat-shader.ts
This PR updates the centers outline to work as expected.
Old:
New:
=> Improve outline mode

src/infinite-grid.ts, src/shaders/infinite-grid-shader.ts
=> Render grid in ortho view

src/main.ts, src/shortcuts.ts
Fixes #232
This PR adds an option to register a keyboard event for capture phase (instead of the default bubble phase). Capture phase handlers are fired first, before any child listeners, allowing global overrides of events.
This is useful for undo/redo which is also handled by entry boxes and results in confusing undo/redo behaviour depending on the currently focused dom element.
This PR also stops propagation of the recognised up and down events and also prevents the default event firing. This is required for capture phase handler, but is probably also desirable for bubble events. This change needs testing.
=> Fix undo/redo keyboard shortcut

src/ui/histogram.ts
This issue as noticed in #360.
The histogram will display no data when encountering NaNs. This PR changes the histogram logic to ignore NaNs and continue plotting non-NaN values.
We should probably display the number of NaN elements encountered on the histogram and also allow users to select these gaussians.
=> Handle NaN data better in histogram

src/anim/spline.ts, src/scene.ts, src/ui/camera-panel.ts
This PR:
- adds cubic (hermite) spline interpolation for camera movement from poses
https://github.com/user-attachments/assets/8fa2c3a9-430a-49a4-8a97-29565d2dba9b
- with the new native project format (which stores camera poses) and camera interpolation, we can now:
- offer the option of exporting animated movies
- export camera spline to html viewer
- improve the camera poses panel considerably
- support multiple camera pose sets
- transform pose sets with gizmos
- support basic delete/insert/modify controls
- display camera poses in the viewport
- support selection of camera pose from 3d viewport
- support for various camera input/export formats (especially nerfstudio format cc @simonbethke)
- approximately another million things
=> Smooth camera animation

src/file-handler.ts, src/splat-serialize.ts, src/ui/publish-settings-dialog.ts
This PR updates the compressed export (and publish) to, by default:
- remove gaussians with alpha < 1 / 255 
- remove gaussians with NaNs or infinites in any of their properties
This is done because we are seeing scenes published which contain a large numbers of invalid gaussian data (in some cases nearly half the scene). These gaussians don't render, but take storage and download space and slow down rendering, significantly in some cases.
=> Export fix

src/doc.ts, src/file-handler.ts
`File > Open`:
Before:
After:
`File > Import`:
Before:
After:
=> [FIX] Limit accepted file types for Open and Import

src/file-handler.ts, src/main.ts, src/ply-sequence.ts, src/ui/timeline-panel.ts
Fixes: #416
This PR fixes PLY sequence loading, which was broken with the introduction of the camera timeline in v2.
- no changes are made to the functionality, ply sequence just loads as before
- sequences should appear as keys on the time which are editable etc, TODO
=> Fix PLY sequences

package-lock.json, package.json, src/camera-poses.ts, src/camera.ts, src/editor.ts, src/file-handler.ts, src/infinite-grid.ts, src/main.ts, src/publish.ts, src/render.ts, src/scene.ts, src/splat-overlay.ts, src/splat.ts, src/sw.ts, src/ui/editor.ts, src/ui/localization.ts, src/ui/menu.ts, src/ui/publish-settings-dialog.ts, src/ui/scss/menu.scss, src/ui/scss/settings-dialog.scss, src/ui/scss/style.scss, src/ui/video-settings-dialog.ts
Fixes: #430
This PR adds support for exporting a video of the camera animation.
The main menu is updated with a new render menu:
Image render works as it did before.
The Render -> Video... option displays a settings dialog:
- only simple export options are available. we can add to these as users put in requests
- transparent background option is not exposed. we can add support for this using webm container (mp4 doesn't support transparent background)
- file is downloaded as usual browser download, we may wish to show file selector popup instead
=> Support video generation

src/data-processor.ts, src/splat-serialize.ts, src/ui/publish-settings-dialog.ts
SuperSplat was exporting normalised camera animation keyframes (based on time) which was changing the spline smoothness since we calculate tangents based on keys.
This PR publishes the frameRate and original key times instead.,
=> Publish camera animation frameRate

src/file-handler.ts, src/ply-sequence.ts
Fixes for loading ply sequences:
- support .ply and .compressed.ply filename convention
- fix bug where sequences with capitals in extension (PLY) weren't correctly ordered
=> Ply sequence fixes

package.json
Actually an earlier build issue we experienced on Windows was due to an npm bug (see [here](https://github.com/npm/cli/issues/7722)).
This PR reverts back to the original build config, but uses `npm ci`, which works with prefix on Windows.
Also remove automatic `git submodule update` call since this clashes with CI.
=> Another build update

src/file-handler.ts, src/pivot.ts, src/ply-sequence.ts, src/ui/bottom-toolbar.ts
This PR makes two changes to the editor defaults:
- place gizmo at the model's origin instead of bounding box center by default
- don't reframe the camera when importing models
Since these settings come up frequently as issues for users.
=> Update default pivot and camera

src/asset-loader.ts, src/data-processor.ts, src/shaders/bound-shader.ts, src/splat.ts
Scenes sometimes contain infinities, which result in invalid bounds being calculated.
This PR skips elements that are infinite during bounds calc.
=> Ignore infinities when calculating bound

src/editor.ts, src/render.ts, src/ui/editor.ts, src/ui/image-settings-dialog.ts, src/ui/localization.ts, src/ui/menu.ts, src/ui/scss/settings-dialog.scss
I created a simple image export dialog with the goal, to support larger resolutions than the viewport of my browser. By doing that, I found that I could/should include more settings that have been copied from the video-export code.
=> Implementation of a render image dialog

src/camera-poses.ts
The original version of drag keyframe has a bug: The pose list may be changed if removed first:
```
const movePose = (index: number, frame: number) => {
// remove target frame pose
const toIndex = poses.findIndex(p => p.frame === frame);
if (toIndex !== -1) {
removePose(toIndex);// List may be changed!!!
}
// move pose
poses[index].frame = frame;
rebuildSpline();
events.fire('timeline.setKey', index, frame);
};
```
So the pose on index should be assigned new value before removing.
=> Fix movePose bug
