playcanvas/supersplat

src/edit-history.ts
src/edit-ops.ts
src/editor-ops.ts
src/ui/control-panel.ts

Fixes: #1 
This PR adds undo and redo for edit operations.

Add support for undo/redo

---

package-lock.json
package.json
src/editor-ops.ts
src/ui/control-panel.ts

This PR adds the option to export to splat export as supported by https://github.com/antimatter15/splat

Add splat export

---

.gitmodules
package-lock.json
package.json
rollup.config.mjs
src/edit-ops.ts
src/editor-ops.ts
src/scene.ts
src/splat.ts
tsconfig.json

This PR updates the codebase to use the engine's splat code.
Also name the downloaded splat files more sanely.

Migrate to engine splat code

---

package-lock.json
package.json
src/editor-ui.ts
src/main.ts
src/spinner.ts
src/style.scss
src/ui/control-panel.ts

Fixes: #27 and #26
This PR updates the UI with a few fixes:
- don't overlap browse button
- only scroll controls, not header and browse bits
- show x/y/z placeholder on vector inputs
- style section headers with uppercase

Fix ui issues

---

.gitmodules
README.md
package-lock.json
package.json
rollup.config.mjs

Since latest engine has been published with GS support, use that instead of submodule.
Fixes #44

Use engine package

---

src/ui/capture-images.ts

signed-url is a post requesst

---

src/editor-ops.ts

an option to preserve thumbnail for edited splat

preserve thumbnail after editing

---

src/tools/picker-selection.ts

Disable contextmenu when picker-selection activated

Disable contextmenu when picker-selection activated

---

src/controllers.ts
src/editor.ts

Fix a couple of type-related warnings.

Fix some tsc compiler errors

---

package-lock.json
package.json
src/manifest.json

Temporary pwa update for default install

Pwa update

---

package-lock.json
package.json

Fixes #96 
The latest engine includes a fix for the gsplat rendering bug.

Update to engine v1.71.2

---

package.json
rollup.config.mjs
src/index.html
src/sw.ts
src/ui/control-panel.ts
tsconfig.json

This PR:
* adds a simple service worker
* application files are cached for offline mode and faster online mode
* updated package to v0.18.0

Add service worker for offline mode

---

package-lock.json
package.json
src/index.html
src/manifest.json
src/sw.ts

This PR updates the recent PWA and SW to work correctly when served from a subfolder.

Fix PWA when served from subfolder

---

package-lock.json
package.json
src/ui/toolbar.ts

Update export icon

---

package-lock.json
package.json
src/tools/transform-tool.ts

Gizmo sizing bug workaround

---

package-lock.json
package.json
src/camera.ts
src/editor.ts
src/splat.ts
src/tools/brush-selection.ts
src/tools/picker-selection.ts
src/tools/rect-selection.ts

Fixes: #118
This PR:
* fixes a bug where points behind the camera were being selected in the rect tool in centers mode
* converts rect, brush and point tool to use pointer events
* capture pointer during drag so button release is correctly handled
* update to latest [Engine v1.72.0](https://github.com/playcanvas/engine/releases/tag/v1.72.0)
* bump package version

Rect select fix

---

package-lock.json
package.json
src/camera.ts
src/controllers.ts
src/scene.ts
src/tools/brush-selection.ts
src/tools/picker-selection.ts
src/tools/rect-selection.ts
src/ui/control-panel.ts
src/ui/editor.ts

This PR:
* converts the camera controls to use pointer events
* enables touch controls on the tool input (rect, brush and picker)
* fixes a keyboard focus button on load
* bumps package version

Support touch input

---

package-lock.json
package.json

Fixes: #124 (hopefully, untested).

Revert sass package

---

package-lock.json
package.json
src/asset-loader.ts
src/file-handler.ts

Fixes: #136
This PR:
* fixes the order of `scale_2` property when loading 2dgs files
* fix for splat placement bug introduced in #137
* bump package version

Small fixes

---

package-lock.json
package.json
src/style.scss
src/tools/brush-selection.ts
src/tools/rect-selection.ts
src/ui/view-cube.ts

This PR:
* fixes an issue where the rect or brush tool can stop working if it is disabled (with keyboard shortcut) while being click-dragged
* fixes and issue with pointer events on the view cube where clicking the background caused the view to orientate strangely

Fix tool bug

---

package-lock.json
package.json
src/camera.ts
src/pc-app.ts

This PR:
* Fix a bug where an additional graphics device was being created at startup
* Bump package version

Graphics device creation fix

---

package-lock.json
package.json
src/editor.ts
src/splat.ts
src/ui/view-panel.ts

Default to rendering with SH

---

src/camera.ts
src/editor.ts
src/ui/view-panel.ts

Adds a Field of View slider to the view options panel. Fixes #175 
https://github.com/user-attachments/assets/83bb05e6-4633-4aa7-a684-73868285bdf0

Add Field of View slider to view options

---

src/edit-history.ts
src/editor.ts
src/file-handler.ts

Clear modified flags and undo/redo history when resetting the scene.

Small edit history fix

---

src/ui/scene-panel.scss
src/ui/scene-panel.ts

Add scrolling on splat list

---

src/ui/localization.ts

Have to test it properly and reread just to be sure :)

Add french support

---

src/ui/localization.ts
src/ui/view-panel.ts

I just did a translation of all the strings to german language. During testing I found that one header wasn't localized yet so I did that one too in german and english.

german-l10n

---

src/asset-loader.ts
src/file-handler.ts
src/main.ts
src/scene.ts

This PR implements loading of .splat file format.
I took @simonbethke 's implementation of `deserializeFromSSplat()` function from #209 and integrated it as simply as possible.

Support loading splat files

---

src/ui/spinner.ts

Hide spinner at load

---

src/ui/view-cube.ts

When clicking the view-cube i often end up with some weird half-rotated view. When checking this again, I found that this happens due to accidential dragging. So I implemneted a quick fix.

View cube bugfix

---

src/ui/color-panel.ts

Small transparency fix

---

src/shaders/sphere-shape-shader.ts
src/sphere-shape.ts

Small PR so sphere visual is less noisy when not covered by splat.

Update sphere shader to work like infinite grid

---

src/tools/lasso-selection.ts

This is a tiny tiny lasso-fix that makes the tondon move smoothly
Before
https://github.com/user-attachments/assets/7a0d5c4e-4597-4421-9a8d-3b1a7f63c438
After
https://github.com/user-attachments/assets/600d8eec-bb6c-4733-88d9-bb5a81643273

tiny lasso fix

---

src/ui/color-panel.ts

Ensure black is less than white to keep color tint panel sane.

Keep black < white

---

src/splat-serialize.ts
src/templates/viewer-html-template.ts

Update HTML Viewer to Web Components 0.1.7

---

src/splat-serialize.ts
src/templates/viewer-html-template.ts

https://github.com/user-attachments/assets/e15e8b47-a7b3-45ea-b6fd-94708baeaaad
* Updates viewer to PlayCanvas Web Components 0.1.9
* Updates viewer to PlayCanvas Engine 2.3.1
* Refactors camera framing to an ESM script
* Enables preload for PLY file
* Restyle UI
* Add XR support

Update viewer to PlayCanvas Web Components 0.1.9

---

src/ui/localization.ts
src/ui/right-toolbar.ts

For camera poses panel and colors panel.

Add missing tooltips

---

src/templates/viewer-html-template.ts

* Adds WebXR based AR mode to the HTML viewer export. Currently only works on Android since iOS still does not support WebXR.
* Updates the button icon SVG.

Add AR mode to HTML viewer

---

src/publish.ts
src/splat-serialize.ts
src/ui/localization.ts

This PR:
- update missing localisations
- fixes a small viewer export bug

Update localisations and viewer bugfix

---

src/splat-serialize.ts
src/templates/viewer-html-template.ts

Fixes: #358
Instead of basing camera clipping plane on scene size we set static near and far planes.

Viewer html fix

---

src/file-handler.ts
src/publish.ts
src/shaders/infinite-grid-shader.ts

Fixes: https://github.com/playcanvas/supersplat/issues/304#issuecomment-2586460277
Various small fixes.

Various small fixes

---

src/pivot.ts
src/splats-transform-handler.ts
src/ui/bottom-toolbar.ts

Fixes for recent gizmo updates

Gizmo fixes

---

src/ui/localization.ts
src/ui/menu.ts
src/ui/viewer-export-popup.ts

Rename 'Scene' menu to 'File'

---

src/ui/transform.ts

resolves https://github.com/playcanvas/supersplat/issues/404

Allow 3 digit precision in position and scale fields

---

src/render.ts
src/ui/localization.ts
src/ui/video-settings-dialog.ts

This PR fixes a few issues with the video support:
- round numbers correctly
- expose low/medium/high/ultra settings for quality instead of Mbps
- label updates

Video output tweaks

---

src/ui/publish-settings-dialog.ts

Small fix, duration is in seconds.

Publish fix

---

src/ui/viewer-export-popup.ts

Fix for html viewer animation export.

Fix for animation exports

---

src/camera-poses.ts
src/file-handler.ts

This PR:
- fixes a bug which meant loading inria cameras.json as poses wasn't working
- also fix a timeline bug when keys exist after the timeline end

Camera pose fixes

---

src/ui/publish-settings-dialog.ts
src/ui/viewer-export-popup.ts

Fixes: #454
Base camera export option on filtered keys.

Camera animation export fix

---

src/render.ts
src/ui/localization.ts
src/ui/video-settings-dialog.ts

Fixes: #475 
This PR adds a user-specified video framerate selection separate from the camera animation framerate.

Add frame rate to video render

---

src/splat-serialize.ts

Fix for seperate/duplicate bug

---

src/asset-loader.ts

Due to API changes in engine v2.8.

Fix for .splat not loading

---

src/ui/menu.ts

The docs have been moved here:
https://developer.playcanvas.com/user-manual/gaussian-splatting/editing/supersplat/

Update User Manual hyperlink

---

src/asset-loader.ts
src/doc.ts
src/file-handler.ts
src/main.ts
src/ply-sequence.ts
src/scene-config.ts

This PR:
- updates loading code to support streaming directly from file where possible
- this should mean faster loading compared to constructing blob and wrapping in URL
- support drag & drop loading of SOGS scenes
- small tweak to default camera FOV

Support sogs loading with drag-and-drop

---

src/publish.ts
src/render.ts
src/ui/editor.ts
src/ui/localization.ts
src/ui/progress.ts
src/ui/scss/progress.scss
src/ui/scss/spinner.scss
src/ui/scss/style.scss

...and use it for publish and video generation.

Add progress bar

---

src/main.ts
src/ply-sequence.ts

Fix for loading files in PWA mode

---

rollup.config.mjs
src/serialize/zip-writer.ts

This PR fixes rollup to use debug engine correctly.
Also fill in some missing parts of zip archive.

Use debug build correctly, zip fixes

---

src/file-handler.ts

Fixed the issue that the same file could not be uploaded again after being deleted.

Allow the same file to be uploaded again after being deleted

---

src/publish.ts
src/ui/localization.ts
src/ui/publish-settings-dialog.ts

Make SOG default when publishing

---

src/asset-loader.ts
src/publish.ts
src/ui/editor.ts
src/ui/localization.ts
src/ui/publish-settings-dialog.ts

This PR:
- adds a publish option to overwrite an existing scene
- we might want more information on the published scenes, like thumbnail
- or perhaps search for scene
- there is pause before showing the publish dialog due to downloading scene list
- currently only the first 128 scenes are shown

Support republish to superspl.at
